// internal/jobs/handler.go
package jobs

import (
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/facets/cur-web/internal/metrics"

	"github.com/facets/cur-web/internal/auth"
	"github.com/facets/cur-web/internal/db"
	"github.com/facets/cur-web/internal/notify"
	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
)

const (
	contentTypeJSON    = "application/json"
	contentTypeHeader  = "Content-Type"
	projectionAuditDir = "projection-audit"
	projectionDuckDB   = "projection.duckdb"
)

type NotifyConfig struct {
	Email    notify.EmailConfig
	SlackURL string
}

type Handler struct {
	db          *db.DB
	jobsDir     string
	spawner     *Spawner
	watcher     *Watcher
	notify      NotifyConfig
	adminEmails []string
}

func NewHandler(d *db.DB, jobsDir string, spawner *Spawner, watcher *Watcher, nc NotifyConfig, adminEmails []string) *Handler {
	return &Handler{db: d, jobsDir: jobsDir, spawner: spawner, watcher: watcher, notify: nc, adminEmails: adminEmails}
}

// isValidJobID returns true only for canonical UUID-format job IDs.
// All job IDs are generated by uuid.New() in Create; rejecting non-UUIDs
// prevents path traversal before any filesystem access.
func isValidJobID(id string) bool {
	_, err := uuid.Parse(id)
	return err == nil
}

// safeJobDir constructs the job directory path for id within baseDir,
// canonicalises it with filepath.Clean, and verifies the result stays strictly
// inside baseDir. Returns ("", false) when id is not a valid UUID or when the
// cleaned path would escape baseDir.
func safeJobDir(baseDir, id string) (string, bool) {
	if !isValidJobID(id) {
		return "", false
	}
	p := filepath.Clean(filepath.Join(baseDir, id))
	base := filepath.Clean(baseDir)
	if p != base && !strings.HasPrefix(p, base+string(os.PathSeparator)) {
		return "", false
	}
	return p, true
}

// sanitizeExt lowercases ext and strips any path-separator characters so it is
// safe to embed in a filepath.Join call. filepath.Ext already guarantees no
// separators, but this makes the sanitization explicit for static analysis.
func sanitizeExt(ext string) string {
	e := strings.ToLower(ext)
	// filepath.Ext never returns a string with OS path separators, but clean
	// any accidental ones to eliminate the taint chain from header.Filename.
	e = strings.ReplaceAll(e, "/", "")
	e = strings.ReplaceAll(e, string(os.PathSeparator), "")
	if e == "" {
		return ".bin"
	}
	return e
}

// canAccess returns true if sess owns the job OR is in the admin list.
// Centralized so every endpoint applies the same rule.
func (h *Handler) canAccess(sess *auth.Session, job *db.Job) bool {
	if sess == nil || job == nil {
		return false
	}
	return job.Owner == sess.Email || sess.IsAdmin(h.adminEmails)
}

func (h *Handler) Create(w http.ResponseWriter, r *http.Request) {
	sess := auth.SessionFromCtx(r.Context())
	r.ParseMultipartForm(200 << 20) // 200 MB
	prospect := r.FormValue("prospect_name")
	if len(prospect) == 0 || len(prospect) > 500 {
		http.Error(w, `{"error":"prospect_name must be 1-500 characters"}`, http.StatusBadRequest)
		return
	}
	file, header, err := r.FormFile("file")
	if err != nil {
		http.Error(w, `{"error":"file required"}`, http.StatusBadRequest)
		return
	}
	defer file.Close()

	// Sanitize the file extension against an allowlist before using it in
	// the filesystem path — this breaks the taint chain from header.Filename.
	// ingest.py handles format detection and writes failure.txt with a clear
	// message if it can't parse the file.
	ext := sanitizeExt(filepath.Ext(header.Filename))
	jobID := uuid.New().String()
	// Use safeJobDir (filepath.Clean + prefix check) even though jobID is
	// server-generated, to satisfy path-traversal static analysis.
	jobDir, _ := safeJobDir(h.jobsDir, jobID)
	if err := os.MkdirAll(jobDir, 0755); err != nil {
		slog.Error("MkdirAll failed", "job_id", jobID, "err", err)
		http.Error(w, `{"error":"storage error"}`, http.StatusInternalServerError)
		return
	}

	dst, err := os.Create(filepath.Join(jobDir, "input"+ext))
	if err != nil {
		http.Error(w, `{"error":"storage error"}`, http.StatusInternalServerError)
		return
	}
	if _, err := io.Copy(dst, file); err != nil {
		dst.Close()
		http.Error(w, `{"error":"file write failed"}`, http.StatusInternalServerError)
		return
	}
	dst.Close()

	// Persist the user-entered prospect name as the deterministic customer name
	// for the report. Phase 6 reads this instead of guessing from the bill
	// (which produced wrong labels like an AWS account ID or a discount line).
	if err := os.WriteFile(filepath.Join(jobDir, "customer_name.txt"), []byte(prospect), 0644); err != nil {
		http.Error(w, `{"error":"storage error"}`, http.StatusInternalServerError)
		return
	}

	if err := h.db.CreateJob(jobID, sess.Email, prospect, ext, jobID); err != nil {
		slog.Error("CreateJob failed", "job_id", jobID, "err", err)
		http.Error(w, `{"error":"storage error"}`, http.StatusInternalServerError)
		return
	}
	metrics.JobsSubmitted.Add(1)
	slog.Info("job submitted", "job_id", jobID, "prospect", prospect, "user", sess.Email, "ext", ext)

	go func() {
		if err := notify.PostJobSubmitted(h.notify.SlackURL, prospect, sess.Email, jobID); err != nil {
			slog.Warn("PostJobSubmitted failed", "job_id", jobID, "err", err)
		}
	}()
	go h.runJob(jobID, jobDir, ext, sess)

	w.Header().Set(contentTypeHeader, contentTypeJSON)
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(map[string]string{"id": jobID, "status": "pending"})
}

func (h *Handler) runJob(jobID, jobDir, ext string, sess *auth.Session) {
	h.db.UpdateJobRunning(jobID)
	pid, err := h.spawner.Start(jobDir, ext, jobID)
	if err != nil {
		h.db.UpdateJobFailed(jobID, "spawn failed: "+err.Error())
		go func() {
			if err := notify.SendJobFailed(h.notify.Email, sess.Email, sess.Name, ""); err != nil {
				slog.Warn("SendJobFailed failed", "job_id", jobID, "err", err)
			}
		}()
		go func() {
			if err := notify.PostJobFailed(h.notify.SlackURL, "", sess.Email, jobID); err != nil {
				slog.Warn("PostJobFailed failed", "job_id", jobID, "err", err)
			}
		}()
		return
	}
	h.db.UpdateJobPID(jobID, pid)
	h.watcher.Watch(jobID, pid)
}

func (h *Handler) List(w http.ResponseWriter, r *http.Request) {
	sess := auth.SessionFromCtx(r.Context())
	jobs, err := h.db.ListJobsByOwner(sess.Email)
	if err != nil {
		http.Error(w, `{"error":"db error"}`, http.StatusInternalServerError)
		return
	}
	if jobs == nil {
		jobs = []*db.Job{}
	}
	w.Header().Set(contentTypeHeader, contentTypeJSON)
	json.NewEncoder(w).Encode(jobs)
}

func (h *Handler) GetByID(w http.ResponseWriter, r *http.Request) {
	sess := auth.SessionFromCtx(r.Context())
	id := chi.URLParam(r, "id")
	if !isValidJobID(id) {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	job, err := h.db.GetJob(id)
	if err != nil {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	if !h.canAccess(sess, job) {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	w.Header().Set(contentTypeHeader, contentTypeJSON)
	json.NewEncoder(w).Encode(job)
}

func (h *Handler) Retry(w http.ResponseWriter, r *http.Request) {
	sess := auth.SessionFromCtx(r.Context())
	id := chi.URLParam(r, "id")
	if !isValidJobID(id) {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	job, err := h.db.GetJob(id)
	if err != nil {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	if !h.canAccess(sess, job) {
		http.Error(w, `{"error":"forbidden"}`, http.StatusForbidden)
		return
	}
	if job.Status != "failed" {
		http.Error(w, `{"error":"can only retry a failed job"}`, http.StatusConflict)
		return
	}

	jobDir := filepath.Clean(filepath.Join(h.jobsDir, id))
	// Remove failure.txt so the watcher doesn't immediately re-fail on the same
	// structural error. The orchestrator reads phase_checkpoint.json at startup
	// and resumes from the next unfinished phase — no manual START_PHASE injection
	// needed and no racy os.Setenv.
	if err := os.Remove(filepath.Join(jobDir, "failure.txt")); err != nil && !os.IsNotExist(err) {
		http.Error(w, `{"error":"could not clear failure state; retry aborted"}`, http.StatusInternalServerError)
		return
	}
	// Remove the orchestrator lock so the new run isn't blocked by a stale PID
	// from the previous attempt (orphaned process or PID reuse on Windows).
	_ = os.Remove(filepath.Join(jobDir, "orchestrator.lock"))

	newSession := uuid.New().String()
	if err := h.db.ResetJobForRetry(id, newSession); err != nil {
		http.Error(w, `{"error":"db reset failed"}`, http.StatusInternalServerError)
		return
	}

	pid, err := h.spawner.Start(jobDir, job.InputExt, newSession)
	if err != nil {
		h.db.UpdateJobFailed(id, "retry spawn failed: "+err.Error())
		// Issue 2: err.Error() can contain quotes/newlines — don't embed in JSON string
		http.Error(w, `{"error":"spawn failed"}`, http.StatusInternalServerError)
		return
	}
	if err := h.db.UpdateJobPID(id, pid); err != nil {
		slog.Error("UpdateJobPID failed after Retry", "job_id", id, "pid", pid, "err", err)
	}
	h.db.UpdateJobRunning(id)
	go h.watcher.Watch(id, pid)

	w.Header().Set(contentTypeHeader, contentTypeJSON)
	w.WriteHeader(http.StatusAccepted)
	json.NewEncoder(w).Encode(map[string]any{"id": id, "status": "running", "pid": pid})
}

func (h *Handler) Refine(w http.ResponseWriter, r *http.Request) {
	sess := auth.SessionFromCtx(r.Context())
	id := chi.URLParam(r, "id")
	if !isValidJobID(id) {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	job, err := h.db.GetJob(id)
	if err != nil {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	if !h.canAccess(sess, job) {
		http.Error(w, `{"error":"forbidden"}`, http.StatusForbidden)
		return
	}
	if job.Status != "done" {
		http.Error(w, `{"error":"can only refine a completed job"}`, http.StatusConflict)
		return
	}
	if job.SessionID == "" {
		http.Error(w, `{"error":"job has no session_id; cannot resume"}`, http.StatusConflict)
		return
	}
	var body struct {
		Instruction string `json:"instruction"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, `{"error":"invalid json"}`, http.StatusBadRequest)
		return
	}
	if len(body.Instruction) < 3 || len(body.Instruction) > 10000 {
		http.Error(w, `{"error":"instruction must be 3-10000 characters"}`, http.StatusBadRequest)
		return
	}

	jobDir := filepath.Clean(filepath.Join(h.jobsDir, id))
	// Issue 8: set running BEFORE spawning so any concurrent poll sees 'running'
	if err := h.db.UpdateJobRunning(id); err != nil {
		http.Error(w, `{"error":"db error"}`, http.StatusInternalServerError)
		return
	}
	pid, err := h.spawner.StartRefine(jobDir, job.SessionID, body.Instruction)
	if err != nil {
		h.db.UpdateJobFailed(id, "refine spawn failed: "+err.Error())
		// Issue 2: err.Error() can contain quotes/newlines — don't embed in JSON string
		http.Error(w, `{"error":"spawn failed"}`, http.StatusInternalServerError)
		return
	}
	// Issue 4: check and log UpdateJobPID errors; non-fatal since watcher still fires
	if err := h.db.UpdateJobPID(id, pid); err != nil {
		slog.Error("UpdateJobPID failed after StartRefine", "job_id", id, "pid", pid, "err", err)
	}
	go h.watcher.WatchOnce(id, pid)

	w.Header().Set(contentTypeHeader, contentTypeJSON)
	w.WriteHeader(http.StatusAccepted)
	json.NewEncoder(w).Encode(map[string]any{"id": id, "status": "refining", "pid": pid})
}

func (h *Handler) Progress(w http.ResponseWriter, r *http.Request) {
	sess := auth.SessionFromCtx(r.Context())
	id := chi.URLParam(r, "id")
	if !isValidJobID(id) {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	job, err := h.db.GetJob(id)
	if err != nil {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	if !h.canAccess(sess, job) {
		http.Error(w, `{"error":"forbidden"}`, http.StatusForbidden)
		return
	}
	jobDir := filepath.Clean(filepath.Join(h.jobsDir, id))
	p, _ := ReadProgress(jobDir, job.SessionID)
	w.Header().Set(contentTypeHeader, contentTypeJSON)
	json.NewEncoder(w).Encode(p)
}

func (h *Handler) Download(w http.ResponseWriter, r *http.Request) {
	sess := auth.SessionFromCtx(r.Context())
	id := chi.URLParam(r, "id")
	if !isValidJobID(id) {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	job, err := h.db.GetJob(id)
	if err != nil {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	if !h.canAccess(sess, job) {
		http.Error(w, `{"error":"forbidden"}`, http.StatusForbidden)
		return
	}
	if job.Status != "done" {
		http.Error(w, `{"error":"report not ready"}`, http.StatusConflict)
		return
	}

	jobDir := filepath.Clean(filepath.Join(h.jobsDir, id))
	runIDParam := r.URL.Query().Get("run_id")

	reportPath, runIDForFilename := resolveReportPath(jobDir, runIDParam)
	if reportPath == "" {
		http.Error(w, `{"error":"no report file found"}`, http.StatusNotFound)
		return
	}

	safeProspect := strings.Map(func(r rune) rune {
		switch r {
		case '"', '/', '\\', '\r', '\n', '\t':
			return '_'
		}
		return r
	}, job.Prospect)
	filename := fmt.Sprintf("%s-gcp-estimate.html", safeProspect)
	if runIDForFilename != "" {
		filename = fmt.Sprintf("%s-gcp-estimate-%s.html", safeProspect, runIDForFilename)
	}
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	w.Header().Set("Content-Type", "text/html")
	http.ServeFile(w, r, reportPath)
}

// resolveReportPath picks the report.html to serve for a Download request.
// Tries, in order:
//   1. Specific run_id from run_results (if runIDParam non-empty)
//   2. Latest row in run_results
//   3. projection-audit/report.html (legacy unsuffixed)
//   4. report.html at the job dir root (very old promotion-era jobs)
// Returns ("", "") if none of those exist on disk. The second return is
// the run_id used (empty for fallback paths) so the caller can embed it
// in Content-Disposition.
func resolveReportPath(jobDir, runIDParam string) (string, string) {
	dbPath := filepath.Join(jobDir, projectionAuditDir, projectionDuckDB)
	runs, _ := QueryRunResults(dbPath) // empty slice on missing db/table

	var pick *RunResult
	if runIDParam != "" {
		for i := range runs {
			if runs[i].RunID == runIDParam {
				pick = &runs[i]
				break
			}
		}
	} else if len(runs) > 0 {
		pick = &runs[0]
	}

	if pick != nil && pick.ReportHTML != nil && *pick.ReportHTML != "" {
		p := filepath.Join(jobDir, *pick.ReportHTML)
		if clean := filepath.Clean(p); !strings.HasPrefix(clean, jobDir+string(filepath.Separator)) {
			return "", ""
		}
		if _, err := os.Stat(p); err == nil {
			return p, pick.RunID
		}
	}
	// Fallback chain for legacy jobs (none of which we expect to keep
	// hitting once BackfillRunResults has covered all existing jobs).
	if p := filepath.Join(jobDir, projectionAuditDir, "report.html"); fileExists(p) {
		return p, ""
	}
	if p := filepath.Join(jobDir, "report.html"); fileExists(p) {
		return p, ""
	}
	return "", ""
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

// Runs returns the run_results history for a job, latest first. Returns
// an empty array (not 404) when the job has no run_results yet — the job
// itself still exists, there's just no run history (very fresh job or
// pre-backfill legacy).
func (h *Handler) Runs(w http.ResponseWriter, r *http.Request) {
	sess := auth.SessionFromCtx(r.Context())
	id := chi.URLParam(r, "id")
	if !isValidJobID(id) {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	job, err := h.db.GetJob(id)
	if err != nil {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	if !h.canAccess(sess, job) {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	dbPath := filepath.Join(h.jobsDir, id, projectionAuditDir, projectionDuckDB)
	runs, err := QueryRunResults(dbPath)
	if err != nil {
		// Issue 6: err.Error() includes full filesystem path — log server-side only
		slog.Error("runs query failed", "job_id", id, "err", err)
		http.Error(w, `{"error":"internal error"}`, http.StatusInternalServerError)
		return
	}
	if runs == nil {
		runs = []RunResult{}
	}
	w.Header().Set(contentTypeHeader, contentTypeJSON)
	json.NewEncoder(w).Encode(runs)
}

// Summary returns the markdown summary for a specific run (or the latest
// run if no run_id query param is provided). 404 when the row has a NULL
// summary_md (legacy/initial backfilled rows) or the file isn't on disk.
func (h *Handler) Summary(w http.ResponseWriter, r *http.Request) {
	sess := auth.SessionFromCtx(r.Context())
	id := chi.URLParam(r, "id")
	if !isValidJobID(id) {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	job, err := h.db.GetJob(id)
	if err != nil {
		http.Error(w, `{"error":"not found"}`, http.StatusNotFound)
		return
	}
	if !h.canAccess(sess, job) {
		http.Error(w, `{"error":"forbidden"}`, http.StatusForbidden)
		return
	}
	jobDir := filepath.Clean(filepath.Join(h.jobsDir, id))
	dbPath := filepath.Join(jobDir, projectionAuditDir, projectionDuckDB)
	runs, err := QueryRunResults(dbPath)
	if err != nil {
		// Issue 6: err.Error() includes full filesystem path — log server-side only
		slog.Error("summary runs query failed", "job_id", id, "err", err)
		http.Error(w, `{"error":"internal error"}`, http.StatusInternalServerError)
		return
	}
	runIDParam := r.URL.Query().Get("run_id")
	var pick *RunResult
	if runIDParam != "" {
		for i := range runs {
			if runs[i].RunID == runIDParam {
				pick = &runs[i]
				break
			}
		}
	} else if len(runs) > 0 {
		pick = &runs[0]
	}
	if pick == nil || pick.SummaryMD == nil || *pick.SummaryMD == "" {
		http.Error(w, `{"error":"summary not available"}`, http.StatusNotFound)
		return
	}
	p := filepath.Join(jobDir, *pick.SummaryMD)
	if clean := filepath.Clean(p); !strings.HasPrefix(clean, jobDir+string(filepath.Separator)) {
		http.Error(w, `{"error":"invalid path"}`, http.StatusForbidden)
		return
	}
	if _, err := os.Stat(p); err != nil {
		http.Error(w, `{"error":"summary file missing"}`, http.StatusNotFound)
		return
	}
	w.Header().Set("Content-Type", "text/markdown; charset=utf-8")
	http.ServeFile(w, r, p)
}

// AdminListAll returns every job across every owner. 403 for non-admins.
// Used by the /admin page in the UI.
func (h *Handler) AdminListAll(w http.ResponseWriter, r *http.Request) {
	sess := auth.SessionFromCtx(r.Context())
	if !sess.IsAdmin(h.adminEmails) {
		http.Error(w, `{"error":"forbidden"}`, http.StatusForbidden)
		return
	}
	jobs, err := h.db.ListAllJobs()
	if err != nil {
		http.Error(w, `{"error":"db error"}`, http.StatusInternalServerError)
		return
	}
	if jobs == nil {
		jobs = []*db.Job{}
	}
	w.Header().Set(contentTypeHeader, contentTypeJSON)
	json.NewEncoder(w).Encode(jobs)
}
